### ISSUE TITLE
Postag with more than 9 characters

### ISSUE THREAD

**Issue by gcelano** [alpheios-project/arethusa#700] opened 2015-07-09 14:46 UTC
Some @postag cotain more than 9 characters. Maybe it is connected to the problem with the underscore/dash one

**Comment by balmas** [comment] 2015-11-02 22:59
@gcelano : I think we determined this was likely caused by manual corrections to the data?

**Comment by gcelano** [comment] 2015-11-02 23:16
Yes, I also think so

**Comment by balmas** [comment] 2015-11-02 23:31
ok, closing then. thanks.

**Closed by balmas** 2015-11-02 23:31 UTC
Labels: unconfirmed
