### ISSUE TITLE
nil in @relation

### ISSUE THREAD

**Issue by gcelano** [alpheios-project/arethusa#759] opened 2016-05-24 09:47 UTC
I see that in @relation there is now the default value "nil", instead of an empty string, as holds true for all the other default values. Can we get back to the empty string for this attribute as well, since this seems to be more coherent and avoids a compatibility issue with Dolphin?

**Comment by balmas** [comment] 2016-06-02 11:42
@gcelano I'm unable to reproduce this. Can you send me a link to a file where it's occurring?

thanks
Bridget

**Comment by balmas** [comment] 2016-06-02 13:04
From @gcelano 

This is a recently created annotation http://www.perseids.org/tools/arethusa/app/#/perseids?chunk=1&doc=33755

the sentences which are not annotated contain a suspicious nil value.

**Comment by balmas** [comment] 2016-06-02 13:05
This is actually not an arethusa bug .. as noted when you annotate a sentence in Arethusa it actually does convert the inital nil value to a blank.  The nils are being inserted when we create a new treebank template in the perseids-client-apps, so I've opened an issue there and am closing this one.

**Closed by balmas** 2016-06-02 13:05 UTC
