### ISSUE TITLE
problem with morph

### ISSUE THREAD

**Issue by vgorman1** [alpheios-project/arethusa#672] opened 2015-04-17 18:19 UTC
My morphology is defaulting back to the computer-chosen forms over the ones I choose. Bridget downloaded  morph_forms and morph_frequency files, but this program will not recognize JSON files, so I cannot attach them here. I will send them to Gernot.

**Comment by balmas** [comment] 2015-04-17 18:31
@lfdm my hypothesis is that it might be defaulting to the users most frequent choice. Not sure if you are still checking in on us but if you are and want to look at this would appreciate it.

**Comment by LFDM** [comment] 2015-04-17 19:55
I am, I am! Will be fixed tomorrow!

**Comment by balmas** [comment] 2015-04-17 19:59
I am reasonably confident it's caused by this line:

https://github.com/latin-language-toolkit/arethusa/commit/3451e0be334b216aa73bbb08a00d70fbce2a5731#diff-0e110681d3c711db23f3a3bd96cc1623R301

together with this:

https://github.com/latin-language-toolkit/arethusa/blob/3451e0be334b216aa73bbb08a00d70fbce2a5731/app/js/arethusa.morph/morph.js#L304

Because we are always overriding and resetting to the most frequent form even if the user explicitly chose something else.  We need to think about how to differentiate.  I am going to comment out the sort in the live environment right now but if you have a better fix for this tomorrow it would be great.  I'm not sure it's going to be super simple.

**Comment by balmas** [comment] 2015-04-17 20:13
commenting out the sort does seem to "fix" the problem so I think my analysis was correct. I think what we need to do is only preselect the most frequent term when there isn't already a selection made by the user, but am not sure we really have the ability to do this right now.

**Comment by balmas** [comment] 2015-04-17 20:14
NB another point about this is that the sorting itself should probably obey the store preferences setting...

**Closed** 2016-03-28 19:32 UTC
